// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.30.0--dev
// source: move.proto

package movepb

import (
	vectorpb "github.com/z5labs/battlebots/pkgs/vectorpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move2DRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Velocity *vectorpb.Vector2      `protobuf:"bytes,1,opt,name=velocity"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Move2DRequest) Reset() {
	*x = Move2DRequest{}
	mi := &file_move_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move2DRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move2DRequest) ProtoMessage() {}

func (x *Move2DRequest) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Move2DRequest) GetVelocity() *vectorpb.Vector2 {
	if x != nil {
		return x.xxx_hidden_Velocity
	}
	return nil
}

func (x *Move2DRequest) SetVelocity(v *vectorpb.Vector2) {
	x.xxx_hidden_Velocity = v
}

func (x *Move2DRequest) HasVelocity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Velocity != nil
}

func (x *Move2DRequest) ClearVelocity() {
	x.xxx_hidden_Velocity = nil
}

type Move2DRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Velocity *vectorpb.Vector2
}

func (b0 Move2DRequest_builder) Build() *Move2DRequest {
	m0 := &Move2DRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Velocity = b.Velocity
	return m0
}

type Move2DResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move2DResponse) Reset() {
	*x = Move2DResponse{}
	mi := &file_move_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move2DResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move2DResponse) ProtoMessage() {}

func (x *Move2DResponse) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Move2DResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Move2DResponse_builder) Build() *Move2DResponse {
	m0 := &Move2DResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Move3DRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Velocity *vectorpb.Vector3      `protobuf:"bytes,1,opt,name=velocity"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Move3DRequest) Reset() {
	*x = Move3DRequest{}
	mi := &file_move_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move3DRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move3DRequest) ProtoMessage() {}

func (x *Move3DRequest) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Move3DRequest) GetVelocity() *vectorpb.Vector3 {
	if x != nil {
		return x.xxx_hidden_Velocity
	}
	return nil
}

func (x *Move3DRequest) SetVelocity(v *vectorpb.Vector3) {
	x.xxx_hidden_Velocity = v
}

func (x *Move3DRequest) HasVelocity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Velocity != nil
}

func (x *Move3DRequest) ClearVelocity() {
	x.xxx_hidden_Velocity = nil
}

type Move3DRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Velocity *vectorpb.Vector3
}

func (b0 Move3DRequest_builder) Build() *Move3DRequest {
	m0 := &Move3DRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Velocity = b.Velocity
	return m0
}

type Move3DResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move3DResponse) Reset() {
	*x = Move3DResponse{}
	mi := &file_move_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move3DResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move3DResponse) ProtoMessage() {}

func (x *Move3DResponse) ProtoReflect() protoreflect.Message {
	mi := &file_move_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Move3DResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Move3DResponse_builder) Build() *Move3DResponse {
	m0 := &Move3DResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_move_proto protoreflect.FileDescriptor

var file_move_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x1a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x49, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x32, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x38, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x62, 0x6f, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x6f,
	0x76, 0x65, 0x32, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x0d,
	0x4d, 0x6f, 0x76, 0x65, 0x33, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a,
	0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x62, 0x6f, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x08, 0x76,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x6f, 0x76, 0x65, 0x33,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x35, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x62, 0x6f, 0x74, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x73, 0x2f, 0x6d,
	0x6f, 0x76, 0x65, 0x70, 0x62, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70,
	0xe8, 0x07,
})

var file_move_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_move_proto_goTypes = []any{
	(*Move2DRequest)(nil),    // 0: battlebots.protobuf.Move2DRequest
	(*Move2DResponse)(nil),   // 1: battlebots.protobuf.Move2DResponse
	(*Move3DRequest)(nil),    // 2: battlebots.protobuf.Move3DRequest
	(*Move3DResponse)(nil),   // 3: battlebots.protobuf.Move3DResponse
	(*vectorpb.Vector2)(nil), // 4: battlebots.protobuf.Vector2
	(*vectorpb.Vector3)(nil), // 5: battlebots.protobuf.Vector3
}
var file_move_proto_depIdxs = []int32{
	4, // 0: battlebots.protobuf.Move2DRequest.velocity:type_name -> battlebots.protobuf.Vector2
	5, // 1: battlebots.protobuf.Move3DRequest.velocity:type_name -> battlebots.protobuf.Vector3
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_move_proto_init() }
func file_move_proto_init() {
	if File_move_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_move_proto_rawDesc), len(file_move_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_move_proto_goTypes,
		DependencyIndexes: file_move_proto_depIdxs,
		MessageInfos:      file_move_proto_msgTypes,
	}.Build()
	File_move_proto = out.File
	file_move_proto_goTypes = nil
	file_move_proto_depIdxs = nil
}
