// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: battle_service.proto

package battlebotspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_battle_service_proto protoreflect.FileDescriptor

const file_battle_service_proto_rawDesc = "" +
	"\n" +
	"\x14battle_service.proto\x12\x13battlebots.protobuf\x1a\x1fstate_change_subscription.proto\x1a\x18state_change_event.proto\x1a\x12move_request.proto\x1a\x13move_response.proto2\xb5\x01\n" +
	"\x06Battle\x12^\n" +
	"\x05State\x12,.battlebots.protobuf.StateChangeSubscription\x1a%.battlebots.protobuf.StateChangeEvent0\x01\x12K\n" +
	"\x04Move\x12 .battlebots.protobuf.MoveRequest\x1a!.battlebots.protobuf.MoveResponseB=Z;github.com/z5labs/battlebots/pkgs/battlebotspb;battlebotspbb\beditionsp\xe8\a"

var file_battle_service_proto_goTypes = []any{
	(*StateChangeSubscription)(nil), // 0: battlebots.protobuf.StateChangeSubscription
	(*MoveRequest)(nil),             // 1: battlebots.protobuf.MoveRequest
	(*StateChangeEvent)(nil),        // 2: battlebots.protobuf.StateChangeEvent
	(*MoveResponse)(nil),            // 3: battlebots.protobuf.MoveResponse
}
var file_battle_service_proto_depIdxs = []int32{
	0, // 0: battlebots.protobuf.Battle.State:input_type -> battlebots.protobuf.StateChangeSubscription
	1, // 1: battlebots.protobuf.Battle.Move:input_type -> battlebots.protobuf.MoveRequest
	2, // 2: battlebots.protobuf.Battle.State:output_type -> battlebots.protobuf.StateChangeEvent
	3, // 3: battlebots.protobuf.Battle.Move:output_type -> battlebots.protobuf.MoveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_battle_service_proto_init() }
func file_battle_service_proto_init() {
	if File_battle_service_proto != nil {
		return
	}
	file_state_change_subscription_proto_init()
	file_state_change_event_proto_init()
	file_move_request_proto_init()
	file_move_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battle_service_proto_rawDesc), len(file_battle_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battle_service_proto_goTypes,
		DependencyIndexes: file_battle_service_proto_depIdxs,
	}.Build()
	File_battle_service_proto = out.File
	file_battle_service_proto_goTypes = nil
	file_battle_service_proto_depIdxs = nil
}
